### ISSUE TITLE
Migrate to SwiftUI lifecycle (Xcode 14)

### ISSUE THREAD

**Issue by ragcsalo** [nickredding/cordova-plugin-apple-watch-link#2]
Can we migrate to the new SwiftUI lifecycle, introduced in Xcode 14? We can't add WatchOS targets like we used to before, so at the moment I'm stuck with WatchOS support for Cordova. :-/

**Comment by nickredding** [comment]
I am in the process of migrating this functionality to Capacitor. Unfortunately, the Cordova framework suffers from poor support and is effectively obsolete. Xcode will respect the targets in existing projects, so the problem is creating new projects. I don't expect the migration to capacitor to be complete until mid-year and I will announce its availability here.
